services:
  - type: web
    name: hiking-assistant
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 8000
    healthCheckPath: /api/health
